server:
  port: 8081
  servlet:
    context-path: /payment-core

integration:
  executor:
    url: "http://localhost:8081"
  clients:
    productClient:
      url: "http://localhost:8080/product-service/api/v1/products"
      connect-timeout: 3s
      read-timeout: 10s